image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py39
  - TOXENV: py310
  - TOXENV: py311
  - TOXENV: py312


build: false

install:
  - py -m pip install --upgrade pip --no-warn-script-location
  - py -m pip install tox

test_script:
  - py -m tox
