site_name: Indiapins
theme:
  name: material
  icon:
      repo: fontawesome/brands/github
  features:
      - navigation.footer
repo_url: https://github.com/pawangeek/indiapins
repo_name: pawangeek/indiapins
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pawangeek
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/in/pawan-jain
